name: Release

run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Submit to CWS
        run: npx chrome-webstore-upload-cli@^3
        env:
          EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: ZIP Chrome
        run: zip -r -FS chrome-${{ github.ref_name }}.zip . --exclude '*/.*' '.*'

      - name: Generate Firefox manifest.json
        run: echo "$(jq -n -S -f manifest.jq)" > ../manifest.json
        working-directory: .manifest

      - name: Submit to AMO
        run: npx web-ext@^8 sign
        env:
          WEB_EXT_API_KEY: ${{ secrets.FIREFOX_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
          WEB_EXT_CHANNEL: listed
          WEB_EXT_APPROVAL_TIMEOUT: 3600000

      - name: Rename Firefox XPI
        run: mv *.xpi firefox-${{ github.ref_name }}.xpi
        working-directory: web-ext-artifacts

      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          preserve_order: true
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          files: |
            chrome-${{ github.ref_name }}.zip
            web-ext-artifacts/firefox-${{ github.ref_name }}.xpi
